stereo_algorithm: 0
prefilter_size: 9
prefilter_cap: 31
correlation_window_size: 15
min_disparity: 28
disparity_range: 256
uniqueness_ratio: 0
texture_threshold: 0
speckle_size: 1000
speckle_range: 31
